copywriter_task:
  description: >
    "Criar mensagens curtas e impactantes para a campanha de {objetivo_campanha} da {nome_loja}, uma loja do segmento de {segmento}."
    " As mensagens devem ser personalizadas para o público-alvo {publico_alvo}, adaptando o tom de voz {tom_de_voz} e utilizando as variáveis disponíveis de forma relevante."
    " Dependendo do tipo de campanha ({tipo_campanha}) – seja 'Data Sazonal', 'Lançamento de produto' ou 'Lançamento de coleção' – a mensagem deve ser ajustada conforme as práticas recomendadas para cada contexto."
  expected_output: |
    Uma mensagem de até 350 caracteres, persuasiva e otimizada para disparos em massa via WhatsApp.
    A mensagem deve ser personalizada e adaptada com base nas variáveis fornecidas, como {{client_first_name}}, {{last_purchase_date}}, {{giftback_code}}, entre outras.
    As variáveis da Zoppy devem permanecer no formato de placeholder (por exemplo, {{client_first_name}}) para que sejam substituídas por outra parte do sistema posteriormente.
    Utilize o tom de voz {tom_de_voz} e certifique-se de que a mensagem ressoe com o público-alvo {publico_alvo} e o objetivo da campanha ({objetivo_campanha}).
    Ajuste o conteúdo para maximizar o impacto de acordo com o tipo de campanha ({tipo_campanha}):
    - Para 'Data Sazonal', enfatize urgência, relevância temporal e temas específicos da data.
    - Para 'Lançamento de produto', destaque novidades, benefícios exclusivos e crie curiosidade.
    - Para 'Lançamento de coleção', foque em tendências, exclusividade e apelo visual.
    Aqui estão alguns exemplos para inspiração:

    **Data Sazonal:**
    '''
    Oi, {{client_first_name}}! 😊

    Aproveitando que a [Nome da Data Sazonal] está chegando, preparamos algo especial para você! É a oportunidade perfeita para garantir uma condição exclusiva e celebrar essa data de um jeito único.

    Não perca tempo e dê uma olhada no que preparamos com tanto carinho! Estamos sempre aqui para o que precisar.

    Com gratidão, 
    Equipe {{company_name}}

    {{store_url}} 
    '''

    **Lançamento de produto:**
    '''
    Oi, {{client_first_name}}! 😊

    Estamos super animados para te contar que acabamos de lançar um novo produto que vai fazer toda a diferença! ✨ Ele foi criado com muito carinho para trazer mais autenticidade para o seu dia a dia.

    Dá uma olhada no nosso site e confira essa novidade que acabou de chegar! Temos certeza de que você vai adorar.

    Se precisar de qualquer coisa, estamos sempre aqui para ajudar!

    Com carinho, 
    Equipe {{company_name}}
    '''

    **Lançamento de coleção:**
    '''
    Oi, {{client_first_name}}! 😊

    Temos uma novidade que mal podemos esperar para compartilhar: nossa nova coleção chegou! 🛍️ Cada peça foi pensada com muito cuidado para trazer o que há de melhor para você.

    Dê uma olhada no site e descubra os novos itens que vão transformar o seu estilo e deixar tudo ainda mais especial.

    Esperamos que você ame tanto quanto nós amamos criar essa coleção para você! 💖

    Com carinho, 
    Equipe {{company_name}}

    {{store_url}}
    '''
