copywriter_task:
  description: >
    "Criar mensagens curtas e impactantes para a campanha de {objetivo_campanha} da {nome_loja}, uma loja do segmento de {segmento}."
    " As mensagens devem ser personalizadas para o público-alvo {publico_alvo}, adaptando o tom de voz {tom_de_voz} e utilizando as variáveis disponíveis de forma relevante."
    " Dependendo do tipo de campanha ({tipo_campanha}) – seja 'Data Sazonal', 'Lançamento de produto' ou 'Lançamento de coleção' – a mensagem deve ser ajustada conforme as práticas recomendadas para cada contexto."
  expected_output: >
    "Uma mensagem de até 350 caracteres, persuasiva e otimizada para disparos em massa via WhatsApp."
    " A mensagem deve ser personalizada e adaptada com base nas variáveis fornecidas, como {client_first_name}, {last_purchase_date}, {giftback_code}, entre outras."
    " Utilize o tom de voz {tom_de_voz} e certifique-se de que a mensagem ressoe com o público-alvo {publico_alvo} e o objetivo da campanha ({objetivo_campanha})."
    " Ajuste o conteúdo para maximizar o impacto de acordo com o tipo de campanha ({tipo_campanha}):"
    - "Para 'Data Sazonal', enfatize urgência, relevância temporal e temas específicos da data."
    - "Para 'Lançamento de produto', destaque novidades, benefícios exclusivos e crie curiosidade."
    - "Para 'Lançamento de coleção', foque em tendências, exclusividade e apelo visual."
    "Aqui estão alguns exemplos para inspiração:"
    '''
    *Oferta Relâmpago de {Data Sazonal} na {nome_loja}!* 

    {{client_first_name}}, aproveite *até 50% OFF* em itens selecionados apenas nesta {Data Sazonal}! Não perca, promoção válida até o final do dia! Acesse: {{company_name}}
    '''
    '''
    *Novidade Exclusiva para Você!* 

    O {novo_produto} acabou de chegar na {nome_loja}! Seja o primeiro a conferir e use o código {{giftback_code}} para 10% de desconto na sua compra. Oferta válida até {{gitback_expiry_date}}. Corre que tá acabando!
    '''
    '''
    *Lançamento da Nova Coleção na {nome_loja}!* 

    {{client_first_name}}, a nova coleção de verão está aqui! Descubra tendências incríveis e garanta suas peças exclusivas com 15% OFF em compras acima de R${{giftback_minimum_purchase_value}}. Visite nossa loja online agora: {{company_name}}
    '''
