copywriter_task:
  description: >
    "Criar mensagens curtas e impactantes para a campanha de {objetivo_campanha} da {nome_loja}, uma loja do segmento de {segmento}."
    "As mensagens devem ser personalizadas para o público-alvo {publico_alvo}, adaptando o tom de voz {tom_de_voz} e utilizando as variáveis disponíveis de forma relevante."
    "Dependendo do tipo de campanha {tipo_campanha} – como \'Data Comemorativa\', \'Lançamento de produto\' ou \'Liquidação\' – a mensagem deve ser ajustada conforme as práticas recomendadas para cada contexto."
     Nao se esqueca de conferir com um humano toda vez que achar que formulou a mensagem final.

     Os inputs fornecidos pelo humano foram: 
     - Nome da loja: {nome_loja}
     - Segmento da loja: {segmento}
     - Público-alvo: {publico_alvo}
     - Tom de voz: {tom_de_voz}
     - Tipo de campanha: {tipo_campanha}
     - Objetivo da campanha: {objetivo_campanha}
  expected_output: >
    Mensagem final de até 350 caracteres, persuasiva e otimizada para disparos em massa via WhatsApp, considerando todos os aspectos da campanha e os inputs fornecidos.

# data_sazonal_task:
#   description: >
#     Criação de uma mensagem adaptada para uma data específica, aproveitando o contexto sazonal para maximizar o impacto.
#   agent: copywriter_data_sazonal
#   inputs:
#     nome_loja: ${nome_loja}
#     segmento: ${segmento}
#     publico_alvo: ${publico_alvo}
#     tom_de_voz: ${tom_de_voz}
#     objetivo_campanha: ${objetivo_campanha}
#     data_especifica: "Data comemorativa específica (e.g., Natal, Dia das Mães)"
#   expected_output: >
#     Uma mensagem persuasiva de até 350 caracteres que ressoe com o público-alvo durante a data sazonal especificada, utilizando o tom de voz e o estilo de comunicação apropriados.

# lancamento_produto_task:
#   description: >
#     Desenvolvimento de uma copy que destaque as características de um novo produto, gerando interesse e incentivando a compra.
#     A tarefa é gerar um modelo de mensagem para a loja {nome_loja}, que atua no segmento {segmento}, com o público-alvo {publico_alvo}, utilizando o tom de voz {tom_de_voz} e com o objetivo de {objetivo_campanha}.
#   agent: copywriter_lancamento_produto
#   expected_output: >
#     Uma mensagem convincente de até 350 caracteres que destaque o novo produto, incentivando o público-alvo a explorar e comprar.

# lancamento_colecao_task:
#   description: >
#     Criação de uma mensagem para promover uma nova coleção, enfatizando tendências, exclusividade e urgência.
#     A tarefa é gerar um modelo de mensagem para a loja {nome_loja}, que atua no segmento {segmento}, com o público-alvo {publico_alvo}, utilizando o tom de voz {tom_de_voz} e com o objetivo de {objetivo_campanha}.
#   agent: copywriter_lancamento_colecao
#   expected_output: >
#     Uma mensagem envolvente de até 350 caracteres que promova a nova coleção, criando um senso de urgência e exclusividade para o público-alvo.

# analise_publico_alvo_task:
#   description: >
#     Adaptação da mensagem para o público-alvo específico, utilizando dados demográficos e comportamentais para garantir relevância e impacto.
#     A tarefa é refinar o modelo de mensagem para a loja {nome_loja}, que atua no segmento {segmento}, com o público-alvo {publico_alvo}, utilizando o tom de voz {tom_de_voz} e com o objetivo de {objetivo_campanha}.
#   agent: analista_publico_alvo
#   expected_output: >
#     Uma mensagem refinada de até 350 caracteres que esteja totalmente alinhada com o perfil do público-alvo, utilizando linguagem, referências culturais e gatilhos emocionais específicos.
